### ISSUE TITLE
Formatting of arguments for resize, ratrelwarp: manpage is unclear, what exactly does "deltax deltay" mean?

### ISSUE THREAD

**Issue by illettante** [dimatura/ratpoison#2]
Trying to resize a window via cli. The manpage documents the arguments resize takes as "resize [deltax deltay]", so i've tried doing:

- ratpoison -c resize 50 110
- ratpoison -c resize delta50 delta110
- ratpoison -c resize Δ50 Δ110
- ratpoison -c resize [50 110]
- ratpoison -c resize [delta50 delta110]
- ratpoison -c resize [Δ50 Δ110]

All of them result in the message "Error : junk arguments <whatever argument out of the above i tried>" except  ratpoison -c resize [Δ50 Δ110] which accepts [Δ50 but returns "Error : junk arguments Δ110]"

What's the format or syntax for resize?

[edit] wanted to label this as a question, but couldn't figure out how. Sorry, i'm not good at stuff [/edit]

**Comment by dimatura** [comment]
I'm not a maintainer of ratpoison or anything, this is just a fork I put on github for my own tweaks. But to answer your question, you would probably want to do `ratpoison -c 'resize 50 110'` (note the quotes - they make the input to `-c` a single "argument" that is interpreted by ratpoison).

**Comment by illettante** [comment]
Thanks, that worked. Sorry to have bugged you with what's probably (now i read your answer) a bit of fundamental bash syntax :/
